---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/users/{id}/posts":
    get:
      summary: Retrieves a post
      tags:
      - Posts
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: post found
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  title:
                    type: string
                  text:
                    type: text
                required:
                - id
                - title
                - text
            application/xml:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  title:
                    type: string
                  text:
                    type: text
                required:
                - id
                - title
                - text
        '404':
          description: post not found
        '406':
          description: unsupported accept header
  "/api/v1/users/{id}/posts/{id}/comments":
    get:
      summary: Retrieves a comment by a user
      tags:
      - Comments
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: post found
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  text:
                    type: text
                required:
                - id
                - text
            application/xml:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  text:
                    type: text
                required:
                - id
                - text
        '404':
          description: post not found
        '406':
          description: unsupported accept header
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
